name: Security audit

on:
  push:
    paths:
      - '.github/workflows/audit.yml'
      - '**/Cargo.toml'

jobs:
  security_audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Generate lockfile
        run: cargo generate-lockfile

      - uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
