name: Tests

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        channel: [ stable, beta, nightly ]

    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Install Rust ${{ matrix.channel }}
        uses: moonrepo/setup-rust@v1
        with:
          bins: cargo-hack
          channel: ${{ matrix.channel }}

      - name: Test powerset
        run: cargo hack test --feature-powerset --optional-deps
